name: giftai
description: App per la generazione di idee regalo personalizzate

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2  # Aggiornato a 11.1.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  
  # Utils
  get_it: ^7.6.0
  intl: ^0.19.0  # Mantenuto a 0.19.0 per compatibilità con flutter_localizations
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  path_provider: ^2.1.1
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  
  # Firebase
  # firebase_core: ^2.15.1
  # firebase_analytics: ^10.4.5
  # firebase_messaging: ^14.6.7
  
  # Auth
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

# AGGIUNGI QUESTA SEZIONE ALLA FINE DEL FILE
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # Configurazione per i font personalizzati, se necessario
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700

# Configurazione per flutter_launcher_icons (opzionale)
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#121212"
  image_dark: assets/images/splash_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"